### ISSUE TITLE
[0.4.5] Looting enchant missing

### ISSUE THREAD

**Issue by GarethCarew** [NillerMedDild/Enigmatica6#1792]
**Modpack version**
0.4.5

**Describe the bug**
The looting enchantment is missing from JEI, and any weapons that had it, no longer do. Running the /enchant command to attempt to enchant a sword with looting, applies Shimmer instead.

**Logs**
N/A

**Screenshots**
Nothing shows up in JEI under the looting tag.
![image](https://user-images.githubusercontent.com/50182665/112190289-d9e52c00-8bd2-11eb-833e-67acd111bf9d.png)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by Thiana** [comment]
+1 to this. My Looting V sword has Shimmer V now :/

**Comment by NillerMedDild** [comment]
Fixed in dev, grabbing the changes from the above commit should do the trick if you want it back quickly :)

**Comment by Thiana** [comment]
Pulling the latest dev doesnt appear to have fixed the issue. The sword is still Shimmer V and the looting enchantment book is still missing.

**Comment by Rodg88** [comment]
Might be worth nothing that some people didn't have this issue, I had looting still available in my install of 0.4.5

**Comment by NillerMedDild** [comment]
Dammit :/ guess I just wasn't affected by the issue then.

**Comment by Rodg88** [comment]
Cofh-core has updated to fix some enchantment bugs, if you have the looting bug it might be worth manually updating it to 1.2.1 to test

**Comment by Thiana** [comment]
Rodg88 is correct, updating to 1.2.1 fixed my swords and the looting enchantment books/tome in JEI.
