### ISSUE TITLE
Bug Carrot Crate Quark spawn in digit dimlet key5 (RfTOOLS Dimensions)

### ISSUE THREAD

**Issue by LiiLk** [NillerMedDild/Enigmatica6#2305]
**Modpack version**
Enigmatica 6 0.4.14 - 1.16.5

**Describe the bug**
With a digit dimlet key5 my friend was created, some block carrot crate mods Quark spawn inside this dimension. however this is not to be spawned.
You can see that with screenshots below.

**Screenshots**
![2021-05-30_12 45 16](https://user-images.githubusercontent.com/61245522/120101335-ed1df600-c145-11eb-810d-3d4a874b72a2.png)
![2021-05-30_12 45 10](https://user-images.githubusercontent.com/61245522/120101350-fe670280-c145-11eb-89e1-54349ed81943.png)
![2021-05-30_12 46 05](https://user-images.githubusercontent.com/61245522/120101355-00c95c80-c146-11eb-918d-56a9eab2b19e.png)
![2021-05-30_12 46 26](https://user-images.githubusercontent.com/61245522/120101373-176fb380-c146-11eb-91e1-f04949f7d5fd.png)
![2021-05-30_12 46 51](https://user-images.githubusercontent.com/61245522/120101376-1b033a80-c146-11eb-8311-5fd46fb2bf90.png)

**Comment by pm065** [comment]
A lot of disabled items are being found in RFTools Dims recently... I don't think there's any way to automate it, since it's controlled by configs. If only startup scripts could access them...
Anyway, this is kind of a duplicate of #2122 and a few others, but I don't think the crates were known to be enabled before

**Comment by NillerMedDild** [comment]
Thanks for reporting, fixed in-dev :)

**Comment by pm065** [comment]
Possible problem in that commit: I still see Potato and Beetroot crates there. I'm fuzzy on the details of this config, but the fact that I see no Carrot Crate anywhere leads me to believe it's a whitelist. Am I correct?

**Comment by NillerMedDild** [comment]
> Possible problem in that commit: I still see Potato and Beetroot crates there. I'm fuzzy on the details of this config, but the fact that I see no Carrot Crate anywhere leads me to believe it's a whitelist. Am I correct? 

You are correct! ty :D
