### ISSUE TITLE
Integrated Dynamics' Energy Battery recipe invalid in crafting interface on world reload

### ISSUE THREAD

**Issue by CosecantX** [NillerMedDild/Enigmatica6#3207]
### Modpack Version

0.5.9 but likely in 0.5.11

### Describe your issue

I couldn't find a report for this on here or the change log, so I assume it's still an issue.

When setting up a crafting interface to allow autocrafting of ID energy batteries, the recipe card is initially accepted and works as intended. However, when the world is quit and reloaded, the recipe is marked as invalid and has to be cleared and replaced with a new, otherwise identical recipe card. As far as I can tell, nothing short of making a new one will actually fix the issue.

### Have you modified the modpack?

Yes

### User Modifications

Optifine

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
I suspect this is fixed in 0.5.11, please try updating :)

**Comment by CosecantX** [comment]
Just tested in 0.5.11, still happening, unfortunately. 
After creating the test network I restarted the game and it happened. I'm not sure if it happens when just reloading the world, but if you can't get the bug to happen with just reloading then try restarting the game.
This instance was completely unmodified. No Optifine, no config changes, etc.
![Untitled](https://user-images.githubusercontent.com/38733763/132939597-4080ebea-6af5-4b60-aa54-ead58cb21a63.png)

**Comment by NillerMedDild** [comment]
Thanks for trying that :D Would you mind also updating the Integrated mod suite? If you'd rather not you can wait for 0.5.12, but there's no ETA on that yet.

**Comment by CosecantX** [comment]
I updated the two Integrated mods that weren't up do date, and the issue still applies. I tried testing some other objects and found that the portable batteries from Powah do the same thing. maybe there's an issue with things that hold RF and start with an empty durability gauge? I'm not a modder so I don't really know the ins and outs of how any of that works.
![Untitled](https://user-images.githubusercontent.com/38733763/132973238-330800ce-6cd8-4f2d-b6a4-c924e4e88d76.png)

**Comment by NillerMedDild** [comment]
Nice, thanks! Could you please provide your latest.log? I'm relaying the issue now :)

**Comment by CosecantX** [comment]
Hope this helps!
[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/7150250/latest.log)

**Comment by NillerMedDild** [comment]
Would you mind putting the below config file in your config folder and see if it fixes the issue? :)
[commoncapabilities-common.zip](https://github.com/NillerMedDild/Enigmatica6/files/7238263/commoncapabilities-common.zip)

**Comment by CosecantX** [comment]
Nope, didn't work, unfortunately. Tested in version 0.5.14.

**Comment by NillerMedDild** [comment]
Alright, thanks for testing 👍

**Comment by rubensworks** [comment]
@CosecantX ID dev here. Could you try loading the following dev builds, open the crafting writer, and re-insert the offending variable cards?
These build will include some debug output in the logs, which will help me debug this issue.
If the logs contain something starting with `Recipe validation failure:`, could you send me the full logs?

* https://github.com/CyclopsMC/packages/packages/769964
* https://github.com/CyclopsMC/packages/packages/770037

(you can just download the asset ending with `[some-version].jar`)

**Comment by CosecantX** [comment]
This is the "recipe validation failure" part:

[03Oct2021 03:26:10.949] [Server thread/INFO] [integratedcrafting/]: Recipe validation failure: incompatible recipe output and simulated output:
Recipe output: [MixedIngredients ingredients: {[IngredientComponent minecraft:itemstack 1736787708]:[integrateddynamics:energy_battery 1 {energy:0}]}]
Simulated output: [MixedIngredients ingredients: {[IngredientComponent minecraft:itemstack 1736787708]:[integrateddynamics:energy_battery 1 null]}]
[03Oct2021 03:26:10.958] [Server thread/INFO] [integratedcrafting/]: Recipe validation failure: incompatible recipe output and simulated output:
Recipe output: [MixedIngredients ingredients: {[IngredientComponent minecraft:itemstack 1736787708]:[integrateddynamics:energy_battery 1 {energy:0}]}]
Simulated output: [MixedIngredients ingredients: {[IngredientComponent minecraft:itemstack 1736787708]:[integrateddynamics:energy_battery 1 null]}]
[03Oct2021 03:26:10.966] [Server thread/INFO] [integratedcrafting/]: Recipe validation failure: incompatible recipe output and simulated output:
Recipe output: [MixedIngredients ingredients: {[IngredientComponent minecraft:itemstack 1736787708]:[integrateddynamics:energy_battery 1 {energy:0}]}]
Simulated output: [MixedIngredients ingredients: {[IngredientComponent minecraft:itemstack 1736787708]:[integrateddynamics:energy_battery 1 null]}]

I've also attached the full log.
[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/7272899/latest.log)

**Comment by rubensworks** [comment]
Thanks for checking @CosecantX! I should have enough information with this to fix the problem.

**Comment by rubensworks** [comment]
@CosecantX Could you try out the latest CommonCaps dev build again? (https://github.com/CyclopsMC/packages/packages/769964)

Together with the config change that @NillerMedDild gave you, this dev build should fix the problem. Could you confirm that this also works on your end?

**Comment by CosecantX** [comment]
that fixed it! thanks!

**Comment by rubensworks** [comment]
Great, thanks for the help @CosecantX!

**Comment by rubensworks** [comment]
@NillerMedDild FYI, in order for this fix to apply, the CommonCapabilities mod will require a config file reset for the next release (or manually making the config change [I mentioned before](https://github.com/CyclopsMC/IntegratedCrafting/issues/68#issuecomment-925032436)).

**Comment by NillerMedDild** [comment]
Thanks, I just applied the change :)
