### ISSUE TITLE
Industrial Foregoing not showing up in a refined storage system

### ISSUE THREAD

**Issue by DarkAngel22579** [NillerMedDild/Enigmatica6#560]
**Modpack version**
0.3.0

**Issue**
IF machines/plastic/etc don't show up in a refined storage system. The manual, dark glass, and buckets like latex all show up, so it looks like an issue with how they're labelled since plastic is under Industrial Foregoing:Core etc.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Works just fine for me, it was probably fixed by one of the mod devs :)

**Comment by DarkAngel22579** [comment]
Issue is still present is version 0.3.2, tested on both the official E6 server and a singlepayer world.

I should have clarified that they show up in the system, but disappear if you search for @ industrial or @ foregoing.

![2021-01-01_12 08 38](https://user-images.githubusercontent.com/74909944/103438368-8514c380-4c2a-11eb-8960-779116b8469d.png)

![2021-01-01_12 09 28](https://user-images.githubusercontent.com/74909944/103438376-8e059500-4c2a-11eb-8e4c-a03dc38de00c.png)

Again seems to be related to how they're labelled
![2021-01-01_12 13 54](https://user-images.githubusercontent.com/74909944/103438458-3582c780-4c2b-11eb-9ba5-5a50655429f5.png)
![2021-01-01_12 13 58](https://user-images.githubusercontent.com/74909944/103438461-37e52180-4c2b-11eb-9b96-252c77d11944.png)
![2021-01-01_12 14 02](https://user-images.githubusercontent.com/74909944/103438462-3a477b80-4c2b-11eb-8e73-52407e1a9546.png)

**Comment by NillerMedDild** [comment]
Ah okay, I'll have another look.

**Comment by NillerMedDild** [comment]
@Buuz135 - Industrial Foregoing items with "custom" mod names such as `Industrial Foregoing: Generators` don't show up in Refined Storage when searching for `@industrial` - Do you think it's an IF or Refined Storage issue?

**Comment by Darkere** [comment]
Probably related to the ":" used. Need to look why that's an issue. But I don't think it's a good idea to use a modname like that. Probably not the only mod checking for ":" to split things.

**Comment by Buuz135** [comment]
JEI seems to handle it fine
