### ISSUE TITLE
Enhanced Astral Sorcery Rituals Trigger ServerHangWatchdog's 300 Second Limit

### ISSUE THREAD

**Issue by r-mc2** [NillerMedDild/Enigmatica6#958]
**Modpack version**
v0.3.5

**Describe the bug**
While I'm sure this is likely an Astral Sorcery specific bug I can't be certain it isn't also some interaction with all the other mods going on, but from my own testing so far regular Astral rituals that require the Ritual Pedestal are more or less fine. However if you go the added step of adding the Enhanced Ritual multiblock (with the additional collector crystal) and beam the added starlight to the Ritual Pedestal something inside Astral is hanging the server. I also tested with and without adding the additional step of using the lenses to reflect the refracted beams back onto the Pedestal that are generated when using the Enhanced version of a ritual. It doesn't seem to affect the tick hanging, the super enhanced with lenses or just plain enhanced both cause it.

Unfortunately it's somewhat inconsistent in the *when*, sometimes it's 20 minutes, sometimes 30, sometimes it's 2 hours. But every time something in their `markDirty` method it's hanging the server on a tick that lasts longer than 5 minutes and triggers the ServerHangWatchdog and the 300 seconds that was updated back in (I think) v0.3.3 of the pack

**Logs**
<details><summary open>Crash Report (Click to Show/Hide)</summary>
<p>
<pre>
---- Minecraft Crash Report ----
// There are four lights!

Time: 1/19/21 12:27 AM
Description: Watching Server

java.lang.Error: ServerHangWatchdog detected that a single server tick took 300.00 seconds (should be max 0.05)
	at hellfirepvp.observerlib.common.util.AlternatingSet.add(AlternatingSet.java:23) ~[observerlib:1.16.4-1.5.0] {re:classloading}
	at hellfirepvp.observerlib.common.data.base.SectionWorldData.lambda$markDirty$0(SectionWorldData.java:48) ~[observerlib:1.16.4-1.5.0] {re:classloading}
	at hellfirepvp.observerlib.common.data.base.SectionWorldData$$Lambda$24792/1617760283.run(Unknown Source) ~[?:?] {}
	at hellfirepvp.observerlib.common.data.CachedWorldData.lambda$write$0(CachedWorldData.java:46) ~[observerlib:1.16.4-1.5.0] {re:classloading}
	at hellfirepvp.observerlib.common.data.CachedWorldData$$Lambda$24788/1956427622.get(Unknown Source) ~[?:?] {}
	at hellfirepvp.observerlib.common.data.CachedWorldData.lock(CachedWorldData.java:83) ~[observerlib:1.16.4-1.5.0] {re:classloading}
	at hellfirepvp.observerlib.common.data.CachedWorldData.write(CachedWorldData.java:45) ~[observerlib:1.16.4-1.5.0] {re:classloading}
	at hellfirepvp.observerlib.common.data.base.SectionWorldData.markDirty(SectionWorldData.java:48) ~[observerlib:1.16.4-1.5.0] {re:classloading}
	at hellfirepvp.astralsorcery.common.starlight.transmission.IPrismTransmissionNode.markDirty(IPrismTransmissionNode.java:126) ~[astralsorcery:1.16.4-1.13.9] {re:classloading}
	at hellfirepvp.astralsorcery.common.tile.network.StarlightReceiverRitualPedestal.doRitualEffect(StarlightReceiverRitualPedestal.java:122) ~[astralsorcery:1.16.4-1.13.9] {re:classloading}
	at hellfirepvp.astralsorcery.common.tile.network.StarlightReceiverRitualPedestal.update(StarlightReceiverRitualPedestal.java:98) ~[astralsorcery:1.16.4-1.13.9] {re:classloading}
	at hellfirepvp.astralsorcery.common.starlight.network.StarlightUpdateHandler.tick(StarlightUpdateHandler.java:49) ~[astralsorcery:1.16.4-1.13.9] {re:classloading}
	at hellfirepvp.observerlib.common.util.tick.TickManager.worldTick(TickManager.java:63) ~[observerlib:1.16.4-1.5.0] {re:classloading}
	at hellfirepvp.observerlib.common.util.tick.TickManager$$Lambda$3884/695737348.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2699/1666726878.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostWorldTick(BasicEventHooks.java:100) ~[forge:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:856) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer$$Lambda$23509/116165474.run(Unknown Source) ~[?:?] {}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271] {}
</pre>
</p>
</details>

**Comment by Darkere** [comment]
I believe this is already fixed. And should be in 0.3.6

**Comment by NillerMedDild** [comment]
I'll close this since it's believed to be resolved already, please let us know if that isn't the case :) Thanks for the report anyhow.

**Comment by r-mc2** [comment]
Fair enough 👍 
Will be upgrading to v0.3.6 tonight and will let you know if I'm still seeing it.

Out of curiosity what was the fix? I didn't see Astral Sorcery get a version bump in the changelog.

**Comment by Darkere** [comment]
The fix was in it's library observerlib
